.Dd June 2019
.Dt MARCUS 1
.Os " "
.Sh NAME
.Nm "Marcus Millin"
.Nd Develop, deploy, and maintain software
.Sh SYNOPSIS
.Nm
.Bl -item
.It
marcusmillin@protonmail.com
.El
.Sh DESCRIPTION
Experienced developer with a passion for open-source,
system administration, DevOps, and software
development.
Skilled in developing and deploying applications across a wide variety of
systems and technologies.
.Sh IMPLEMENTATION NOTES
Languages, tools, and environments:
.D1 Ansible, C#, Docker, gRPC, Git, JavaScript, Kubernetes, Mandoc, Perl, Perl6, Python, Rust, SQL, Shell (bash/ksh), Terraform, Unix/Linux, Vagrant
.Sh ENVIRONMENT
Currently working in the Southern Wisconsin area,
but open to working anywhere within the United States.
.Sh EXAMPLES
.Ss QBE Insurance -- Sun Prairie, Wi -- (Nov 2012 - Present)
.Ss Senior Developer (July 2017 - Present)
.Bd -ragged
Overview:
Helped implement DevOps practices while working with a wide variety of
technologies.
Managed technologies used for deployment including Kubernetes, Docker,
Jenkins, and a variety of Azure cloud services.
Worked across several codebases and technologies in order to facilitate working with
geospacial data, machine learning, distributed computing, and telematics data.
.Ed
.Bd -ragged
Key Accomplishments:
.Bl -bullet
.It
Built several back-end APIs using Python with Flask and Django.
.It
Lead pilot usage of Kubernetes and containerized deployment.
.It
Architected and built platform for distributed machine-learning on geospacial
images using Docker, Kubernetes, Python, and Celery.
.It
Mentored and guided team members to become proficient with tools like Git, Docker,
and Kubernetes.
.It
Split time across several projects to guide architecture and technology
decisions. Implemented and enforced git branching strategy, coding standards,
and code review.
.It
Senior title earned September 2018 (don't take too seriously).
.El
.Ed
.Ss Infrastructure Intern (June 2015 - June 2017)
.Bd -ragged
Overview:
Helped end-user compute team with software roll out, device management, and
operating system deployment.
In addition to this, created and managed a custom application to help other
technicians to perform these actions.
.Ed
.Bd -ragged
Key Accomplishments:
.Bl -bullet
.It
Created and supported C#.NET application for tier 2 and 3 technicians to more
easily interface with SCCM and Active Directory, giving them the ability to 
perform essential job duties after migrations.
.It
Wrote several programs and scripts to automate the migration of applications
from legacy software management system.
.It
Facilitated the deployment and upgrading of software across thousands of
end-user computing devices.
.El
.Ed
.Ss Desktop Support Intern (November 2012 - August 2014)
.Bd -ragged
Overview:
Worked on the Desktop Support team doing tier 2 technical support for
employees.
Support included both hardware and software issues, user training, installing
software, configuring new devices, and working on a desktop modernization
project.
Handled over 400 customer incidents and requests.
Created custom tools using VB.NET and Powershell to help fellow technicians 
better automate their work.
.Ed
.Ss University of Wisconsin-Madison -- Madison, Wi (Jan 2017 - May 2017)
.Ss Peer Mentor - Introduction to Algorithms (CS577)
.Bd -ragged
Overview:
Helped fellow students with general algorithm concepts and techniques including
greedy algorithms, randomness, network flow, dynamic programming, and divide
and conquer in one-on-one sessions.
.Ed
.Sh EDUCATION
.Ss University of Wisconsin - Madison
.Ss Bachelor of Science - Computer Science
