.Dd May 2018
.Dt MARCUS 1
.Os
.Sh NAME
.Nm "Marcus Millin"
.Nd Develop software
.Sh SYNOPSIS
.Nm
.Bl -item
.It
marcusmillin@protonmail.com
.El
.Sh DESCRIPTION
Software developer with a passion for open-source, system administration,
DevOps, and software development.
Proficient with Python, the unix command line, and Kubernetes.
Experienced in developing using bleeding-edge concepts and technologies
including IoT devices, Blockchain, Machine-Learning / Artificial Intelligence,
and more.
.Sh IMPLEMENTATION NOTES
Languages, tools, and environments I am able to program in/with.
.D1 C, C#, Docker, gRPC, Git, GraphViz, Java, Kubernetes, LaTeX, Mandoc, Perl, Perl6, Python, Rust, SQL, Shell (bash/ksh), Solidity, Unix/Linux, Vagrant
.Sh ENVIRONMENT
Looking for work in the southern Wisconsin area, anywhere in Montana, or remote.
.Sh EXAMPLES
.Ss QBE Insurance -- Sun Prairie, Wi -- (Nov 2012 - Present)
.Ss Senior Developer (July 2017 - Present)
.Bd -ragged
Overview:
Worked on several agile teams and helped implement DevOps practices while
working with a wide variety of technologies.
Many projects consisted of backend web-development with python, including
geospacial data, machine learning, distributed computing, telematics
data.
.Ed
.Bd -ragged
Key Accomplishments:
.Bl -bullet
.It
Built backend and managed deployment for telematics data presentation.
.It
Lead Kubernetes usage for company using Azure's Kubernetes service.
.It
Architected and built platform for distributed machine-learning on geospacial
images using Docker, Kubernetes, Python, and Celery.
.It
Created a custom Ethereum based private blockchain using a Proof-of-Authority
consensus protocol.
.It
Adapted machine-learning models for object detection in images using the
Tensorflow library.
.It
Senior title achieved September 2018.
.El
.Ed
.Ss Infrastructure Intern (June 2015 - June 2017)
.Bd -ragged
Overview:
Helped end-user compute team in many aspects including software roll out, 
device management via SCCM and AD, and operating system deployment.
In addition to working on the creation and 
.Ed
.Bd -ragged
Key Accomplishments:
.Bl -bullet
.It
Created and supported C#.NET application for tier 2 and 3 technicians to better
interface with SCCM and Active Directory, giving them the ability to perform
essential job duties after migrations.
.It
Created several custom reports to monitor the status of software deployment and
licensing to assist Asset Management in data standardization, collection, and storage.
.It
Wrote several programs and scripts to automate the migration of applications
from legacy software management system to new management environment.
.It
Facilitated the deployment and upgrading of software accross thousands of
end-user computing devices, both physical and virtual.
.El
.Ed
.Ss Desktop Support Intern (November 2012 - August 2014)
.Bd -ragged
Overview:
Worked on the Desktop Support team doing tier 2 technical support for employees 
both on site and remote.
Support included both hardware and software issues, user training, installing
software, configuring new devices, and working on a desktop modernization
project.
Personally handled over 400 customer incidents and requests.
Additionally, created custom tools using VB.NET and Powershell to help fellow
technicians better automate their work.
.Ed
.Ss University of Wisconsin-Madison -- Madison, Wi (Jan 2017 - May 2017)
.Ss Peer Mentor - Introduction to Algorithms (CS577)
.Bd -ragged
Overview:
Helped fellow students with general algorithm concepts and techniques including
greedy algorithms, randomness, network flow, dynamic programming, and divide
and conquer in a one-on-one setting.
.Ed
